[tool.poetry]
name = "audgit"
version = "0.1.0"
description = ""
authors = ["Christopher David <chris@arcadelabs.co>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.scripts]
audgit = "src.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
